### ISSUE TITLE
Readme.md Review

### ISSUE THREAD

**Issue by kg2k1b** [rickjunli/DAT_SF_16#2]
Hi Rick, i was able to look at your Readme.md file. Seems like you were able to create the Readme.md without any issues, but i didn't see any thing about you in this file. Maybe, that text or the changes didn't get pushed to your GitHub repo?

**Comment by kg2k1b** [comment]
@ghego @Breucopter
what do you say? how are we doing so far?

**Comment by rickjunli** [comment]
Hi Karan,

There are several Readme.md files in my repo. Did you look under the directory called finalproject? That's where my Readme.md file with my description is located. 

I am not 100% clear who is supposed to review whose work. I think you are right (you are my reviewer), At first glance though, I thought I was supposed to review yours. 

@ghego @Breucopter could you guys confirm?

Thanks.

**Comment by kg2k1b** [comment]
Rick,
You are right. I didn't look in that folder. I apologize.
Everything seems to be in order.
Thank you,
Karan

**Comment by rickjunli** [comment]
No problem. Glad you found it.

**Comment by ghego** [comment]
I see why the file may be creating some confusion. I'll send a message to explain it.

Congrats! You found how to cite us!
Keep rocking!!

(you can close the issue now)
