### ISSUE TITLE
HW5 notes

### ISSUE THREAD

**Issue by Breucopter** [rickjunli/DAT_SF_16#7]
Hey Rick,

So figured out why your data scores poorly on the non-normalized: just a typo! Otherwise the hw looks great, plots are thorough. Your assignment of classes is a bit circuitous. Using df.map({'benign':0,'malignant':1}) is more efficient and avoids that settingwithcopy warning.

**Comment by rickjunli** [comment]
Thanks Justin. I would have never found that typo! :)
